### ISSUE TITLE
Cannot build or generate with nuxt 3.4.3

### ISSUE THREAD

**Issue by igorjacauna** [nuxt-themes/alpine#132]
I juste created a new project with Nuxt 3.4.3 and got error on build and generate

See this: https://stackblitz.com/edit/github-kv47kh

Run the `npm run generate` or `npm run build`

Shows:

```
 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)                                                             15:32:50
file: /home/projects/github-kv47kh/node_modules/@nuxt-themes/typography/components/global/ProseCodeInline.vue?vue&type=style&index=0&scoped=e2e5456a&lang.ts?inline&used:1:5
1: code{font-family:var(--typography-font-code);border-radius:var(--prose-code-inline-borderRadius);padding:var(--prose-...
        ^


 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)                                                             15:32:50

  at error (file://node_modules/rollup/dist/es/shared/node-entry.js:2150:30)
  at Module.error (file://node_modules/rollup/dist/es/shared/node-entry.js:13477:16)
  at Module.tryParse (file://node_modules/rollup/dist/es/shared/node-entry.js:14188:25)
  at Module.setSource (file://node_modules/rollup/dist/es/shared/node-entry.js:13790:39)
  at ModuleLoader.addModuleSource (file://node_modules/rollup/dist/es/shared/node-entry.js:23755:20)
```

Maybe something with Pinceau? I don't know how starts a investigation to help fix.

**Comment by Tahul** [comment]
Hey, this has been fixed by Nuxt `3.5.0`.

I'm closing this but feel free to re-open if you encounter it again!
