### ISSUE TITLE
500 Cannot redefine property: $bodyLock when visite https://elements.nuxt.space/ 

### ISSUE THREAD

**Issue by DevDengChao** [nuxt-themes/alpine#156]
1. visit https://alpine.nuxt.space/
2. click the `30+ built-in components`
![image](https://github.com/nuxt-themes/alpine/assets/16363180/0a24b4a5-ae25-43da-b936-bf3c8e5cd6f5)
3. Boom
![image](https://github.com/nuxt-themes/alpine/assets/16363180/70a38053-e404-4663-9b33-b548b9febe9a)

```log
[nuxt] error caught during app initialization TypeError: Cannot redefine property: $bodyLock
    at Function.defineProperty (<anonymous>)
    at Ir (entry.07415002.js:1:89089)
    at Sm.n.provide (entry.07415002.js:1:87366)
    at Rm (entry.07415002.js:1:87928)
    at async Om (entry.07415002.js:1:88082)
    at async Nc (entry.07415002.js:14:29314)
```

**Comment by mGGk-fr** [comment]
Same here !

**Comment by dosstx** [comment]
I can't access the page either, but anyone else concerned it hasn't been fixed since July?

**Comment by KazooTTT** [comment]
encountered the same problem

**Comment by lukkamvd2** [comment]
Same problem here!

**Comment by donovanglover** [comment]
This seems like a serious issue and no response is concerning. As a workaround, can the link be changed or removed?

**Comment by HtmAl** [comment]
I was about to report it myself... Interesting that it would take so long to fix a broken link.

**Comment by leafleaf90** [comment]
Still getting the same...
