### ISSUE TITLE
 ERROR  Cannot find module '@nuxt/ui-templates'   

### ISSUE THREAD

**Issue by msrody** [nuxt-themes/alpine#199]
I'm unable to build or generate because of the error. 

I have found that '@nuxt/ui-templates'   is no longer used but have not been able to track down how to make the build process stop looking for it.

**Comment by msrody** [comment]
I'll try again.

I am unable to build alpine, though it will display properly in dev.

```  
yarn build
yarn run v1.22.22
warning ../../package.json: No license field
$ nuxi build
[9:09:10 AM] Nuxt 3.12.2 with Nitro 2.9.7

[9:09:18 AM]  ERROR  Cannot find module '@nuxt/ui-templates'
Require stack:
- /home/msrody/Workspace/blog/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
  at Function.resolve (node:internal/modules/cjs/helpers:116:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:241814)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2225:29)
  at node_modules/nuxt-component-meta/dist/module.mjs:103:17
  at node_modules/hookable/dist/index.mjs:48:66
  at Object.run (node_modules/hookable/dist/index.mjs:41:43)
  at node_modules/hookable/dist/index.mjs:48:56
  at async node_modules/nuxt/dist/index.mjs:2199:7
  at async resolveApp (node_modules/nuxt/dist/index.mjs:5185:3)
  at async generateApp (node_modules/nuxt/dist/index.mjs:5034:3)
  at async _applyPromised (node_modules/perfect-debounce/dist/index.mjs:54:10)



[9:09:18 AM]  ERROR  Cannot find module '@nuxt/ui-templates'
Require stack:
- /home/msrody/Workspace/blog/index.js

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
It will not build in Cloudfare pages nor on my dev server. It has not built properly for about 1 month, I was away from the project for a while so not sure what happened in the mean time.

**Comment by securixhk** [comment]
Hey @msrody,
Did you find a solution/workaround on Vercel :) ?
Parallel thread : https://github.com/nuxt/nuxt/issues/27592 
Thanks

**Comment by securixhk** [comment]
Adding
`    "@nuxthq/studio": "^2.0.3",`

To **devDependencies** of the package.json file, fixes the issue.

**Comment by msrody** [comment]
> Adding ` "@nuxthq/studio": "^2.0.3",`
> 
> To **devDependencies** of the package.json file, fixes the issue.

Thank you.  This simple fix worked and it's building again. 

Thank you.
